az_rg_name                  = "TemplateBuilderWorker"
az_rg_location              = "westus"
az_vnet_name                = "builderWorkerVnet"
az_pub_ip_name              = "builderWorkerPubIP"
az_pub_ip_allocation_method = "Static"
az_nsg_name                 = "builderWorkerNetSecGroup"
